require("chrigi.options")
require("chrigi.keymaps")
require("chrigi.plugins")
require("chrigi.colorscheme")
require("chrigi.treesitter")
require("chrigi.cmp")
require("chrigi.lsp")
require("chrigi.telescope")
require("chrigi.autopairs")
require("chrigi.comment")
require("chrigi.gitsigns")
require("chrigi.nvim-tree")
require("chrigi.bufferline")
require("chrigi.toggleterm")
require("chrigi.lualine")
require("chrigi.project")
require("chrigi.impatient")
require("chrigi.indentline")
require("chrigi.alpha")
require("chrigi.dap") -- Needs to be after lsp as soon as manson is used
require("chrigi.todo-comments")
require("chrigi.trouble")
require("chrigi.whichkey")

-- TODO read into autocommands:
--require("chrigi.autocommands")
